config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :rooms do
        resources :messages
      end
    end
  end

  Rails.application.routes.draw do
    resources :rooms do
      resources :messages
    end
  end
  
  # Defines the root path route ("/")
  root "rooms#index"
  resources :rooms do
    resources :messages
  end
  devise_for :users
  # resources :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_commit { broadcast_append_to "room_#{room.id}"}
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :messages, dependent: :destroy
end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all

    render json: @rooms
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @book = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @book = Room.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = Room.find(params[:room_id]).messages
    render json: @messages
  end

  def create
    @message = current_user.messages.build(message_params)
    @message.room_id = params[:room_id]

    if @message.save
      render json: @message, status: :created
    else
      render json: @message.errors, status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all

    # render json: @rooms
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @messages = @room.messages
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<%= react_component("Hello", { name: "react-rails" }) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatRoomsRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="px-5 py-2"> 
     <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="flex flex-col w-full">
  <%= simple_form_for([@room, Message.new], data:{
    action: "turbo:submit-end->messages#resetForm", messages_target: "input_form"
  }) do |f| %>
    <div class="flex items-center space-x-4">
      <%= f.input :body, label: false, input_html: {placeholder: "Type your message", class: "w-full px-4 py-2 border rounded-lg focus:outline-none shadow-lg focus:ring-2 focus:ring-blue-500"}, wrapper_html: {class: "flex-1"} %>
      <%= f.submit "Send", class: "bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>
  <% end %>
</div>

app/views/messages/_message.html.erb
<%= turbo_frame_tag dom_id(message) do %>
  <div class="flex items-center my-3">
    <div class="w-8 h-8 mr-2 overflow-hidden rounded-full">
      <img src="https://ui-avatars.com/api/?name=<%= message.user.email.split('@')[0].capitalize %>" class="object-cover w-full h-full" alt="">
    </div>
    <div class="text-sm text-gray-700">
      <%= "#{message.user.email.split('@')[0].capitalize}: #{message.body}" %>
    </div>
  </div>
<% end %>

app/views/rooms/_form.html.erb
<div class="flex items-center justify-center min-h-screen bg-gray-50">
  <div class="w-full max-w-md p-8 bg-white rounded-lg shadow-md">
    <h2 class="mb-6 text-2xl font-bold text-center">Manage Room</h2>

    <%= form_with(model: room, local: true) do |form| %>
      <% if room.errors.any? %>
        <div class="p-4 mb-4 text-red-700 bg-red-100 border border-red-400 rounded">
          <h2 class="text-lg font-semibold"><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>
          <ul class="mt-2 list-disc list-inside">
            <% room.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-4">
        <%= form.label :name, class: "block mb-2 text-sm font-medium text-gray-700" %>
        <%= form.text_field :name, class: "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>

      <div>
        <%= form.submit "Create Room", class: "w-full px-4 py-2 text-white bg-blue-500 rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/_room.html.erb
<div class="container mx-auto my-3 rounded-lg shadow-lg">
  <div class="flex flex-col"> 
    <div>
    <header-component />
    </div>
    <div class="flex flex-row my-3 bg-white">
      <div class="w-2/6 mt-2"> 
        <room-list-component/>
      </div>
      <div class="w-4/6">
        <div class="flex flex-col justify-between w-full px-5">
        <div id="<%= dom_id room %>" data-controller="messages" class="flex flex-col mt-2">
  <%= turbo_stream_from dom_id(room) %>
  
  <div id="messages" data-messages-target="container">
    <% @messages&.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>
  
  <div id="new_message" class="flex items-center m-4">
    <img src="https://t4.ftcdn.net/jpg/05/89/93/27/360_F_589932782_vQAEAZhHnq1QCGu5ikwrYaQD0Mmurm0N.webp" class="object-cover w-8 h-8 rounded-full" alt="">
    <%= render "messages/form", room: room %>
  </div>
</div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/default_room.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mx-auto my-3 rounded-lg shadow-lg">
  <div class="flex flex-col"> 
    <div>
      <header-component />
    </div>
    <div class="flex flex-row my-3 bg-white">
      <div class="w-2/6 mt-2"> 
        <room-list-component/>
      </div>
      <div class="w-4/6">
          <div class="flex items-center justify-center h-full" data-messages-target="container">
            <h1 class="text-2xl font-bold text-center">Pick Room First at Left</h1>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
  
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mx-auto my-3 rounded-lg shadow-lg">
  <div class="flex flex-col"> 
    <div>
      <header-component />
    </div>
    <div class="flex flex-row my-3 bg-white">
      <div class="w-2/6 mt-2"> 
        <room-list-component/>
      </div>
      <div class="w-4/6">
          <div class="flex items-center justify-center h-full" data-messages-target="container">
            <h1 class="text-2xl font-bold text-center">Pick Room First at Left</h1>
          </div>
      </div>
    </div>
  </div>
</div>
<div class="container flex items-end justify-end p-4 mx-auto my-3 bg-gray-200 rounded shadow-lg">
  <div class="flex items-end">
    <%= link_to "New room", new_room_path, class: "bg-green-600 hover:bg-green-800 rounded p-3 text-white mr-4" %>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p class="text-green-500"><%= notice %></p>

<%= render @room %>

    <div class="container flex items-center justify-between p-4 mx-auto my-3 bg-gray-200 rounded shadow-lg">
      <div class="flex items-center">
        <%= link_to "Edit this room", edit_room_path(@room), class: "bg-yellow-600 hover:bg-yellow-800 p-3 rounded text-white bg- mr-4" %>
        <%= link_to "New room", new_room_path, class: "bg-green-600 hover:bg-green-800 rounded p-3 text-white mr-4" %>
      
      </div>
      <%= button_to "Destroy this room", @room, method: :delete, data: { confirm: "Are you sure?" }, class: "text-red-500 bg-transparent hover:bg-red-500 transition ease-in-out delay-50  hover:text-white border border-red-500 hover:border-transparent py-2 px-4 rounded" %>
    </div>